export const siteUrl = "https://andantino-shoes.jp";
export const lastmod = "2026-08-18";

const page = (file, priority) => ({
  file,
  path: file === "index.html" ? "/" : `/${file.replace(/\.html$/, "")}`,
  priority
});

export const pages = [
  page("index.html", "1.0"),
  page("about.html", "0.9"),
  page("owner.html", "0.9"),
  page("adult-shoes.html", "0.9"),
  page("childrens-shoes.html", "0.9"),
  page("products.html", "0.8"),
  page("product-kenplanter-pumps.html", "0.6"),
  page("product-kenplanter-boots.html", "0.6"),
  page("product-paramount-pumps.html", "0.6"),
  page("product-comfort-bolognese.html", "0.6"),
  page("product-superfit.html", "0.6"),
  page("product-branca.html", "0.6"),
  page("product-dragon-insole.html", "0.6"),
  page("product-mizutori-geta.html", "0.6"),
  page("product-mizutori-zori.html", "0.6"),
  page("product-support-socks.html", "0.6"),
  page("insoles.html", "0.9"),
  page("dymoco-insole.html", "0.6"),
  page("pricing.html", "0.9"),
  page("seminars.html", "0.8"),
  page("for-professionals.html", "0.7"),
  page("guides.html", "0.9"),
  page("shoe-wearing.html", "0.9"),
  page("foot-problems.html", "0.8"),
  page("hallux-valgus.html", "0.7"),
  page("tailors-bunion.html", "0.7"),
  page("foot-arch.html", "0.7"),
  page("leg-length-discrepancy.html", "0.7"),
  page("knee-pain.html", "0.7"),
  page("foot-check.html", "0.8"),
  page("nordic-walking.html", "0.6"),
  page("case-studies.html", "0.6"),
  page("articles.html", "0.8"),
  page("articles-children.html", "0.6"),
  page("articles-adult.html", "0.6"),
  page("articles-foot-problems.html", "0.6"),
  page("articles-insoles.html", "0.6"),
  page("articles-shoe-wearing.html", "0.6"),
  page("online-consultation.html", "0.7"),
  page("pdf-products.html", "0.6"),
  page("faq.html", "0.8"),
  page("contact.html", "0.9"),
  page("news.html", "0.6"),
  page("links.html", "0.6"),
  page("privacy.html", "0.4"),
  page("terms.html", "0.4"),
  page("legal.html", "0.5")
];
