export const siteUrl = "https://www.andantino-shoes.jp";
export const lastmod = "2026-07-27";

export const pages = [
  { file: "index.html", path: "/", priority: "1.0" },
  { file: "about.html", path: "/about", priority: "0.9" },
  { file: "owner.html", path: "/owner", priority: "0.9" },
  { file: "adult-shoes.html", path: "/adult-shoes", priority: "0.9" },
  { file: "childrens-shoes.html", path: "/childrens-shoes", priority: "0.9" },
  { file: "products.html", path: "/products", priority: "0.8" },
  { file: "product-kenplanter-pumps.html", path: "/product-kenplanter-pumps", priority: "0.6" },
  { file: "product-kenplanter-boots.html", path: "/product-kenplanter-boots", priority: "0.6" },
  { file: "product-paramount-pumps.html", path: "/product-paramount-pumps", priority: "0.6" },
  { file: "product-comfort-bolognese.html", path: "/product-comfort-bolognese", priority: "0.6" },
  { file: "product-superfit.html", path: "/product-superfit", priority: "0.6" },
  { file: "product-branca.html", path: "/product-branca", priority: "0.6" },
  { file: "product-dragon-insole.html", path: "/product-dragon-insole", priority: "0.6" },
  { file: "product-mizutori-geta.html", path: "/product-mizutori-geta", priority: "0.6" },
  { file: "product-mizutori-zori.html", path: "/product-mizutori-zori", priority: "0.6" },
  { file: "product-support-socks.html", path: "/product-support-socks", priority: "0.6" },
  { file: "insoles.html", path: "/insoles", priority: "0.9" },
  { file: "dymoco-insole.html", path: "/dymoco-insole", priority: "0.6" },
  { file: "pricing.html", path: "/pricing", priority: "0.9" },
  { file: "seminars.html", path: "/seminars", priority: "0.8" },
  { file: "for-professionals.html", path: "/for-professionals", priority: "0.7" },
  { file: "guides.html", path: "/guides", priority: "0.9" },
  { file: "shoe-wearing.html", path: "/shoe-wearing", priority: "0.9" },
  { file: "foot-problems.html", path: "/foot-problems", priority: "0.8" },
  { file: "hallux-valgus.html", path: "/hallux-valgus", priority: "0.7" },
  { file: "tailors-bunion.html", path: "/tailors-bunion", priority: "0.7" },
  { file: "foot-arch.html", path: "/foot-arch", priority: "0.7" },
  { file: "leg-length-discrepancy.html", path: "/leg-length-discrepancy", priority: "0.7" },
  { file: "knee-pain.html", path: "/knee-pain", priority: "0.7" },
  { file: "foot-check.html", path: "/foot-check", priority: "0.8" },
  { file: "nordic-walking.html", path: "/nordic-walking", priority: "0.6" },
  { file: "case-studies.html", path: "/case-studies", priority: "0.6" },
  { file: "articles.html", path: "/articles", priority: "0.8" },
  { file: "articles-children.html", path: "/articles-children", priority: "0.6" },
  { file: "articles-adult.html", path: "/articles-adult", priority: "0.6" },
  { file: "articles-foot-problems.html", path: "/articles-foot-problems", priority: "0.6" },
  { file: "articles-insoles.html", path: "/articles-insoles", priority: "0.6" },
  { file: "articles-shoe-wearing.html", path: "/articles-shoe-wearing", priority: "0.6" },
  { file: "online-consultation.html", path: "/online-consultation", priority: "0.7" },
  { file: "pdf-products.html", path: "/pdf-products", priority: "0.6" },
  { file: "faq.html", path: "/faq", priority: "0.8" },
  { file: "contact.html", path: "/contact", priority: "0.9" },
  { file: "news.html", path: "/news", priority: "0.6" },
  { file: "links.html", path: "/links", priority: "0.6" },
  { file: "privacy.html", path: "/privacy", priority: "0.4" },
  { file: "terms.html", path: "/terms", priority: "0.4" },
  { file: "legal.html", path: "/legal", priority: "0.5" }
];
