export const siteUrl = "https://www.andantino-shoes.jp";
export const lastmod = "2026-07-27";

export const pages = [
  { file: "index.html", path: "/", priority: "1.0" },
  { file: "about.html", path: "/about.html", priority: "0.9" },
  { file: "owner.html", path: "/owner.html", priority: "0.9" },
  { file: "adult-shoes.html", path: "/adult-shoes.html", priority: "0.9" },
  { file: "childrens-shoes.html", path: "/childrens-shoes.html", priority: "0.9" },
  { file: "products.html", path: "/products.html", priority: "0.8" },
  { file: "product-kenplanter-pumps.html", path: "/product-kenplanter-pumps.html", priority: "0.6" },
  { file: "product-kenplanter-boots.html", path: "/product-kenplanter-boots.html", priority: "0.6" },
  { file: "product-paramount-pumps.html", path: "/product-paramount-pumps.html", priority: "0.6" },
  { file: "product-comfort-bolognese.html", path: "/product-comfort-bolognese.html", priority: "0.6" },
  { file: "product-superfit.html", path: "/product-superfit.html", priority: "0.6" },
  { file: "product-branca.html", path: "/product-branca.html", priority: "0.6" },
  { file: "product-dragon-insole.html", path: "/product-dragon-insole.html", priority: "0.6" },
  { file: "product-mizutori-geta.html", path: "/product-mizutori-geta.html", priority: "0.6" },
  { file: "product-mizutori-zori.html", path: "/product-mizutori-zori.html", priority: "0.6" },
  { file: "product-support-socks.html", path: "/product-support-socks.html", priority: "0.6" },
  { file: "insoles.html", path: "/insoles.html", priority: "0.9" },
  { file: "dymoco-insole.html", path: "/dymoco-insole.html", priority: "0.6" },
  { file: "pricing.html", path: "/pricing.html", priority: "0.9" },
  { file: "seminars.html", path: "/seminars.html", priority: "0.8" },
  { file: "for-professionals.html", path: "/for-professionals.html", priority: "0.7" },
  { file: "guides.html", path: "/guides.html", priority: "0.9" },
  { file: "shoe-wearing.html", path: "/shoe-wearing.html", priority: "0.9" },
  { file: "foot-problems.html", path: "/foot-problems.html", priority: "0.8" },
  { file: "hallux-valgus.html", path: "/hallux-valgus.html", priority: "0.7" },
  { file: "tailors-bunion.html", path: "/tailors-bunion.html", priority: "0.7" },
  { file: "foot-arch.html", path: "/foot-arch.html", priority: "0.7" },
  { file: "leg-length-discrepancy.html", path: "/leg-length-discrepancy.html", priority: "0.7" },
  { file: "knee-pain.html", path: "/knee-pain.html", priority: "0.7" },
  { file: "foot-check.html", path: "/foot-check.html", priority: "0.8" },
  { file: "nordic-walking.html", path: "/nordic-walking.html", priority: "0.6" },
  { file: "case-studies.html", path: "/case-studies.html", priority: "0.6" },
  { file: "articles.html", path: "/articles.html", priority: "0.8" },
  { file: "articles-children.html", path: "/articles-children.html", priority: "0.6" },
  { file: "articles-adult.html", path: "/articles-adult.html", priority: "0.6" },
  { file: "articles-foot-problems.html", path: "/articles-foot-problems.html", priority: "0.6" },
  { file: "articles-insoles.html", path: "/articles-insoles.html", priority: "0.6" },
  { file: "articles-shoe-wearing.html", path: "/articles-shoe-wearing.html", priority: "0.6" },
  { file: "online-consultation.html", path: "/online-consultation.html", priority: "0.7" },
  { file: "pdf-products.html", path: "/pdf-products.html", priority: "0.6" },
  { file: "faq.html", path: "/faq.html", priority: "0.8" },
  { file: "contact.html", path: "/contact.html", priority: "0.9" },
  { file: "news.html", path: "/news.html", priority: "0.6" },
  { file: "links.html", path: "/links.html", priority: "0.6" },
  { file: "privacy.html", path: "/privacy.html", priority: "0.4" },
  { file: "terms.html", path: "/terms.html", priority: "0.4" },
  { file: "legal.html", path: "/legal.html", priority: "0.5" }
];
